#!/usr/bin/env python3
"""Create deterministic, original grayscale inputs for Part 8.1."""

import hashlib
import io
import json
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFilter

ROOT = Path(__file__).resolve().parent.parent
SIZE = 2048
SEED = 542
TITLES = {
    "geometry": "Geometric edges",
    "frequency": "Fine textures",
    "soft_scene": "Soft synthetic scene",
}


def geometry():
    ramp = np.broadcast_to(np.linspace(28, 88, SIZE), (SIZE, SIZE)).copy()
    img = Image.fromarray(np.rint(ramp).astype(np.uint8))
    draw = ImageDraw.Draw(img)
    draw.rectangle((180, 180, 900, 860), fill=190)
    draw.rectangle((290, 290, 780, 730), fill=65)
    draw.ellipse((1120, 170, 1880, 930), fill=235)
    draw.ellipse((1280, 330, 1720, 770), fill=125)
    draw.polygon(((230, 1810), (650, 1020), (1060, 1810)), fill=215)
    for i in range(8):
        x = 1160 + i * 88
        draw.line((x, 1130, x + 75, 1780), fill=225, width=12 + i * 3)
    return img


def frequency():
    y, x = np.mgrid[0:SIZE, 0:SIZE].astype(np.float64) / SIZE
    pixels = np.full((SIZE, SIZE), 128.0)
    a = (x < 0.5) & (y < 0.5)
    b = (x >= 0.5) & (y < 0.5)
    c = (x < 0.5) & (y >= 0.5)
    d = (x >= 0.5) & (y >= 0.5)
    pixels[a] = (128 + 85 * np.sin(2 * np.pi * (8 * x + 170 * x * x)))[a]
    radius = np.hypot(x - 0.75, y - 0.25)
    pixels[b] = (128 + 85 * np.sin(2 * np.pi * 180 * radius * radius))[b]
    checker = (np.floor(x * 96) + np.floor(y * 96)).astype(int) % 2
    pixels[c] = (65 + 125 * checker)[c]
    pixels[d] = (128 + 65 * np.sin(2 * np.pi * 85 * (x + y)))[d]
    img = Image.fromarray(np.clip(np.rint(pixels), 0, 255).astype(np.uint8))
    ImageDraw.Draw(img).rectangle((1008, 0, 1040, SIZE), fill=128)
    ImageDraw.Draw(img).rectangle((0, 1008, SIZE, 1040), fill=128)
    return img


def soft_scene():
    rng = np.random.default_rng(SEED)
    y = np.linspace(185, 85, SIZE)[:, None]
    pixels = np.broadcast_to(y, (SIZE, SIZE)) + rng.normal(0, 1.5, (SIZE, SIZE))
    img = Image.fromarray(np.clip(np.rint(pixels), 0, 255).astype(np.uint8))
    draw = ImageDraw.Draw(img)
    draw.ellipse((1450, 180, 1720, 450), fill=230)
    draw.polygon(((0, 1170), (350, 520), (690, 960), (1040, 570),
                  (1500, 1130), (1780, 660), (2048, 1040), (2048, 1500),
                  (0, 1500)), fill=110)
    draw.rectangle((0, 1280, SIZE, SIZE), fill=72)
    draw.rectangle((550, 950, 1360, 1570), fill=166)
    draw.polygon(((440, 970), (955, 560), (1470, 970)), fill=48)
    draw.rectangle((895, 1180, 1080, 1570), fill=50)
    for left in (650, 1140):
        draw.rectangle((left, 1080, left + 140, 1240), fill=225)
        draw.line((left + 70, 1080, left + 70, 1240), fill=78, width=15)
        draw.line((left, 1160, left + 140, 1160), fill=78, width=15)
    draw.rectangle((1660, 850, 1730, 1580), fill=45)
    for box in ((1460, 680, 1810, 1130), (1570, 430, 1870, 900),
                (1690, 710, 1990, 1150)):
        draw.ellipse(box, fill=90)
    for left in range(80, 2010, 130):
        draw.rectangle((left, 1710, left + 35, 1950), fill=192)
    draw.rectangle((40, 1790, 2020, 1820), fill=190)
    return img.filter(ImageFilter.GaussianBlur(radius=5))


def main():
    folder = ROOT / "data" / "images"
    folder.mkdir(parents=True, exist_ok=True)
    records = []
    for name, factory in (("geometry", geometry), ("frequency", frequency),
                          ("soft_scene", soft_scene)):
        img = factory()
        buffer = io.BytesIO()
        img.save(buffer, format="PNG", compress_level=9)
        content = buffer.getvalue()
        path = folder / f"{name}.png"
        if path.exists() and path.read_bytes() != content:
            raise SystemExit(f"Refusing to replace different existing input: {path}")
        path.write_bytes(content)
        records.append({"name": name, "title": TITLES[name],
                        "path": path.relative_to(ROOT).as_posix(),
                        "sha256": hashlib.sha256(content).hexdigest(),
                        "size": [SIZE, SIZE], "mode": "L"})
        print(f"Created {path.relative_to(ROOT)}", flush=True)
    manifest = {"origin": "Original procedural test patterns generated by this repository; no external images.",
                "generator": "scripts/generate_test_images.py", "seed": SEED,
                "images": records}
    (folder / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")


if __name__ == "__main__":
    main()
